language: ruby

jdk: openjdk8

cache:
  - bundler

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bundle exec rake publish

notifications:
  slack:
    secure: YE9LirevstqJ9qglWo2C1IrFEObyThgS72ks0oikEyqKyx1UeEljX3OPX03k+fref/3Z2smtAMH2OgCaXi3cpLIDJI3J14EXOyzMHYz1ul1h52Qp5UrwbKIikD4Yi+RywVLGhLZMedKKI1D0MwcHlwSEuATyIJpZ7do28lEcuL0=

deploy:
  provider: s3
  bucket: support.dnsimple.com
  region: us-west-2
  skip_cleanup: true
  local_dir: output
  cache_control: "max-age=86400"
  acl: public_read
  edge: true
